services: 
  nginx:
    image: nginx:alpine
    container_name: nginx
    # restart: unless-stopped
    ports:
      - "80:80"
    volumes: 
      - ./public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
     

  mysql:
    image: mysql
    container_name: mysql
    # restart: unless-stopped

    ports: 
      - "3306:3306"
    # volumes: 
    #   - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  redis:
    image: redis:alpine
    container_name: redis
    # restart: unless-stopped
    ports:
      - 6379:6379
    # volumes:
    #   - ./redis:/data

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    # restart: unless-stopped
    ports:
      - 27017:27017
    # volumes:
    #   - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
 
  app:
    image: daniellee860911/leave-api-php-8-2
    container_name: laravel
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    # restart: unless-stopped
    # volumes:
    #   - ./:/var/www
    ports:
      - "9000:9000"
    depends_on: 
      - mysql
      - redis
      - mongodb

    